#!/bin/bash
set -e

APP_USER="${HORPLUS_APP_DB_USER:-horplus_app}"
APP_PASS="${HORPLUS_APP_DB_PASSWORD:-password}"

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  DO \$\$
  BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '$APP_USER') THEN
      CREATE ROLE $APP_USER WITH LOGIN PASSWORD '$APP_PASS' NOSUPERUSER NOBYPASSRLS;
    ELSE
      ALTER ROLE $APP_USER WITH LOGIN PASSWORD '$APP_PASS' NOSUPERUSER NOBYPASSRLS;
    END IF;
  END \$\$;

  GRANT USAGE ON SCHEMA public TO $APP_USER;
  GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO $APP_USER;
  GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO $APP_USER;

  ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO $APP_USER;
  ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO $APP_USER;
EOSQL
